version: '3.8'

services:

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
    ports:
      - "9094:9094"
    networks: [data-network]
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-init:
    image: apache/kafka:3.7.0
    container_name: kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    networks: [data-network]
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        echo "Создание топиков"

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic transactions.valid \
          --partitions 3 \
          --replication-factor 1 \
          --config retention.bytes=3221225472 \
          --config segment.bytes=104857600

        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create --if-not-exists \
          --topic transactions.invalid \
          --partitions 3 \
          --replication-factor 1 \
          --config retention.bytes=3221225472 \
          --config segment.bytes=104857600

        echo "Топики созданы:"
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --describe \
          --topic transactions.valid,transactions.invalid

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks: [data-network]

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: clickhouse
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_NATIVE}:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse/init:/docker-entrypoint-initdb.d
      - ./clickhouse/config:/etc/clickhouse-server/users.d
    networks: [data-network]


  superset:
    image: apache/superset:3.1.0
    container_name: superset
    ports:
      - "${SUPERSET_PORT}:8088"
    depends_on:
      clickhouse:
        condition: service_started
    environment:
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    volumes:
      - superset_data:/app/superset_home
    networks: [data-network]
    command: >
      bash -c "
      superset db upgrade &&
      superset fab create-admin
        --username ${SUPERSET_ADMIN_USERNAME}
        --firstname Admin
        --lastname Admin
        --email ${SUPERSET_ADMIN_EMAIL}
        --password ${SUPERSET_ADMIN_PASSWORD} || true &&
      superset init &&
      superset run -p 8088 --host 0.0.0.0
      "

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      - POSTGRES_USER=${AIRFLOW_DB_USER}
      - POSTGRES_PASSWORD=${AIRFLOW_DB_PASSWORD}
      - POSTGRES_DB=${AIRFLOW_DB_NAME}
    networks: [data-network]
    volumes:
      - airflow_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AIRFLOW_DB_USER} -d ${AIRFLOW_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

  airflow-init:
    build: .
    container_name: airflow-init
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
    networks: [data-network]
    depends_on:
      airflow-db:
        condition: service_healthy
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true
      "

  airflow-webserver:
    build: .
    container_name: airflow-webserver
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - AIRFLOW__WEBSERVER__SHOW_TRIGGER_FORM_IF_NO_PARAMS=True
    volumes:
      - ./dags:/opt/airflow/dags
    networks: [data-network]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      clickhouse:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "${AIRFLOW_PORT}:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    env_file: .env
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db/${AIRFLOW_DB_NAME}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW_EXECUTOR}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
    volumes:
      - ./dags:/opt/airflow/dags
    networks: [data-network]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      clickhouse:
        condition: service_started
      kafka:
        condition: service_healthy
    command: airflow scheduler

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter
    ports:
      - "${JUPYTER_PORT}:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    volumes:
      - ./notebooks:/home/jovyan/work
    working_dir: /home/jovyan/work
    command: start-notebook.sh --notebook-dir=/home/jovyan/work
    networks: [data-network]

  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    container_name: fastapi_producer
    ports:
      - "${FASTAPI_PORT}:8000"
    env_file: .env
    volumes:
      - ./notebooks/Financial_Transactions_Enriched.csv:/app/data/Financial_Transactions_Enriched.csv:ro
    depends_on:
      kafka:
        condition: service_healthy
      kafka-init:
        condition: service_completed_successfully
    restart: unless-stopped
    networks: [data-network]

networks:
  data-network:
    driver: bridge

volumes:
  kafka_data:
  airflow_db_data:
  clickhouse_data:
  superset_data: